### ISSUE TITLE
Crosswalk 11 zip file is ignored if present

### ISSUE THREAD

**Issue by baleboy** [crosswalk-project/crosswalk-app-tools#27]
I have crosswalk-11.40.277.6.zip in the same folder as crosswalk-app-tools, but when I run 

crosswalk-app-tools/bin/crosswalk-app create org.xwalk.hello

The tool still tries to download crosswalk for 01.org

**Comment by r0b5t4** [comment]
11 is beta at the moment, App-tools always tries to use the latest stable by default. I will add an option so you can specify a particular release on the command line.

**Comment by baleboy** [comment]
Somehow I think the logic should be, first check if there is a local one, if not go to the network to ask what is stable etc.

**Comment by r0b5t4** [comment]
Isn't the danger then that an unsuspecting developer will accidentally create and deploy packages with an old version?

**Comment by baleboy** [comment]
yes that's true. No changes in the plan then :)
