### ISSUE TITLE
The result should be separated by 'release' and 'debug'

### ISSUE THREAD

**Issue by takethathe** [crosswalk-project/crosswalk-app-tools#32]
After built the project, the result should be classified as 'release' or 'debug' version, by place the target into different folders, like 'pkg/release' and 'pkg/debug'

**Comment by r0b5t4** [comment]
Not sure about this. It is easier having to look in just one place after the build.

**Comment by takethathe** [comment]
Some platform might have the same target name for 'release' and 'debug' build.

**Comment by r0b5t4** [comment]
I think only the most recent build should be in the pkg/ directory. Otherwise there could be a confusion, and the developer could debug the wrong build, or publish an old build. Older builds should be deleted before the start of the next build.

**Comment by r0b5t4** [comment]
Keeping all packages in the same dir for now.
