### ISSUE TITLE
The package id style should not only for Android

### ISSUE THREAD

**Issue by takethathe** [crosswalk-project/crosswalk-app-tools#34]
A package id like 'org.crosswalk-project.Crosswalk-App-Tool' is illegal one for Android platform, but is an acceptable one for iOS, so it's better to implement the package id checker it in backend, not in framework.

**Comment by r0b5t4** [comment]
Good point, but I am not sure this is a very important issue. Do you think it is ok to only allow the very restrictive android compliant packages for the moment?

**Comment by takethathe** [comment]
Agree, but it's better to document in some place, and become a part of Crosswalk Project spec.

**Comment by r0b5t4** [comment]
Moved to https://crosswalk-project.org/jira/browse/XWALK-3826
